workspace = { members = ["stiletto_macros"] }
[package]
name = "stiletto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stiletto_macros = { path = "stiletto_macros" }
once_cell = "1.19.0"
