name: dirk - Test

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always


jobs:
  insta:

    name: Snapshot testing
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check Rust version
      run: cargo --version

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.0
      with:
        shared-key: "Insta"
           
    - name: Build
      run: cargo build --workspace --test errors --test examples --verbose
    
    - name: Run tests
      run: cargo test --workspace --verbose --no-fail-fast --test errors --test examples

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


  doctest:

    name: Doctests
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check Rust version
      run: cargo --version

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.0
      with:
        shared-key: "Doctest"
           
    - name: Build
      run: cargo build --workspace --verbose
    
    - name: Run tests
      run: cargo test --workspace --verbose --no-fail-fast --doc

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
