name: dirk - Publish

on:
  release:
    types: [published]

jobs:
  semver-checks:

    name: Semver Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check Rust version
      run: cargo --version

#    - name: Rust Cache
#      uses: Swatinem/rust-cache@v2.7.0
#      with:
#        shared-key: "SemverChecks"
           
    - name: Semver Checks
      uses: obi1kenobi/cargo-semver-checks-action@v2

  publish:
    
    name: Publish
    needs: semver-checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check Rust version
      run: cargo --version

    - name: Install toml-cli
      run: cargo install toml-cli

    - name: Check version
      run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"

    - name: Publish
      run: cargo publish
      env:            
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
